name: Deploy to ModelScope Studio

on:
  push:
    branches: [modelscope-deploy]

jobs:
  deploy-to-modelscope:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to ModelScope Studio
        env:
          MODELSCOPE_TOKEN: ${{ secrets.MS_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add modelscope https://oauth2:$MODELSCOPE_TOKEN@modelscope.cn/studios/OhMyDearAI/hawarma-preview.git
          git push modelscope modelscope-deploy:master