name: Deploy to Hugging Face Space

on:
  push:
    branches: [huggingface-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://oh-my-dear-ai:$HF_TOKEN@huggingface.co/spaces/oh-my-dear-ai/hawarma-preview
          git push --force space huggingface-deploy:main