name: Deploy to Hugging Face Space

on:
  push:
    branches: [huggingface-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.png"
          git add .gitattributes
          # Remove all tracked files and re-add them to ensure LFS tracking
          git rm --cached -r .
          git add .
          git commit -m "Migrate images to Git LFS" || echo "No changes to commit"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://oh-my-dear-ai:$HF_TOKEN@huggingface.co/spaces/oh-my-dear-ai/hawarma-preview
          git push --force space huggingface-deploy:main